node('ose-agent') {
    
    def WORKSPACE = pwd()
    def mvnHome = tool 'maven'
   
   stage 'Checkout'

       checkout scm

   stage 'Maven Deploy'
      sh """
      ${mvnHome}/bin/mvn clean deploy -DskipTests       
      """
}
