#!/bin/sh

#Kick off kjar job when pom changes

git config --global user.email 'gogs@redhat.com'

echo "work in progress remote"

git push origin master:master

echo "Checking to see if pom changed during commit"

git show --pretty="" --name-only HEAD | grep 'pom\.xml' &> /dev/null

if [ $? == 0 ]; then

echo "change to pom, pushing to master branch"

git push origin master:deployments

fi
